/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.avirato.gui;

import com.avirato.controller.GuiMainController;
import com.avirato.model.Customer;
import com.avirato.model.service.Data;
import com.avirato.model.service.Datum;
import com.avirato.service.UserApiService;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;


/**
 *
 * @author Cristian
 */
public class GuiMain extends javax.swing.JFrame{
    
    private GuiMainController guiMainController = new GuiMainController();
    private UserApiService userApiService = new UserApiService();
    private DefaultTableModel jTableDefaultModel;
    private TableRowSorter<TableModel> sorter;
    private ActionListener taskPerformer;
    private boolean editTextFields = false;
    
    
    
    
    /**
     * Creates new form GuiMain
     * @throws java.io.IOException
     */
    public GuiMain() throws IOException {
        initComponents();
        setLocation(200, 200);
        setTitle("Avirato Gestor de Clientes");
        setIconImage(new ImageIcon("C:\\Users\\Cristian\\Documents\\NetBeansProjects"
                + "\\Avirato\\src\\main\\resources\\IconoAvirato.png").getImage());
        populateCustomerTable();
        clearMessageBox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelTable = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableCustomer = new javax.swing.JTable();
        jTextFieldFilter = new javax.swing.JTextField();
        jButtonClearFilters = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldMessages = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jButtonSendEditCostumer = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldName = new javax.swing.JTextField();
        jTextFieldPhone = new javax.swing.JTextField();
        jTextFieldEmail = new javax.swing.JTextField();
        jTextFieldBirthDate = new javax.swing.JTextField();
        jLabelCustomerEdit = new javax.swing.JLabel();
        jButtonCancelEditCostumer = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldId = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jButtonCrear = new javax.swing.JButton();
        jButtonModificar = new javax.swing.JButton();
        jButtonEliminar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jButtonListAll = new javax.swing.JButton();
        jButtonIdSearch = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuFile = new javax.swing.JMenu();
        jMenuExit = new javax.swing.JMenuItem();
        jMenuHelp = new javax.swing.JMenu();
        jMenuAbout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(400, 300));
        setResizable(false);

        jPanelTable.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTableCustomer.setAutoCreateRowSorter(true);
        jTableCustomer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
            },
            new String [] {
                "Id", "Nombre", "Teléfono", "Correo", "Fecha Nac."
            }
        ));
        jTableCustomer.setCellSelectionEnabled(false);
        jTableCustomer.setName(""); // NOI18N
        jTableCustomer.setRowSelectionAllowed(true);
        jTableCustomer.setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        jTableCustomer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableCustomerMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableCustomer);
        jTableCustomer.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTableCustomer.getColumnModel().getColumn(0).setWidth(20);
        jTableCustomer.getColumnModel().getColumn(1).setWidth(20);
        jTableCustomer.getColumnModel().getColumn(2).setWidth(60);
        jTableCustomer.getColumnModel().getColumn(3).setWidth(60);

        jTextFieldFilter.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextFieldFilter.setToolTipText("");
        jTextFieldFilter.setMaximumSize(new java.awt.Dimension(350, 21));
        jTextFieldFilter.setMinimumSize(new java.awt.Dimension(350, 21));
        jTextFieldFilter.setPreferredSize(new java.awt.Dimension(350, 21));
        jTextFieldFilter.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldFilterKeyTyped(evt);
            }
        });

        jButtonClearFilters.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButtonClearFilters.setText("Limpiar filtros");
        jButtonClearFilters.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClearFiltersActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Filtro:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Listado de Clientes");
        jLabel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTextFieldMessages.setEditable(false);
        jTextFieldMessages.setBackground(new java.awt.Color(229, 229, 229));
        jTextFieldMessages.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jTextFieldMessages.setForeground(new java.awt.Color(255, 0, 0));
        jTextFieldMessages.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldMessages.setToolTipText("");
        jTextFieldMessages.setMaximumSize(new java.awt.Dimension(350, 21));
        jTextFieldMessages.setMinimumSize(new java.awt.Dimension(350, 21));
        jTextFieldMessages.setPreferredSize(new java.awt.Dimension(350, 21));
        jTextFieldMessages.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldMessagesKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanelTableLayout = new javax.swing.GroupLayout(jPanelTable);
        jPanelTable.setLayout(jPanelTableLayout);
        jPanelTableLayout.setHorizontalGroup(
            jPanelTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTableLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelTableLayout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                        .addComponent(jButtonClearFilters))
                    .addComponent(jTextFieldMessages, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelTableLayout.setVerticalGroup(
            jPanelTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTableLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanelTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanelTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(jButtonClearFilters))
                    .addComponent(jTextFieldFilter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldMessages, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButtonSendEditCostumer.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButtonSendEditCostumer.setText("Enviar");
        jButtonSendEditCostumer.setEnabled(false);
        jButtonSendEditCostumer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSendEditCostumerActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Nombre");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Telefono");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Correo");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Fecha nacimiento");

        jTextFieldName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextFieldName.setEnabled(false);
        jTextFieldName.setMaximumSize(new java.awt.Dimension(148, 21));
        jTextFieldName.setMinimumSize(new java.awt.Dimension(148, 21));
        jTextFieldName.setPreferredSize(new java.awt.Dimension(148, 21));

        jTextFieldPhone.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextFieldPhone.setEnabled(false);
        jTextFieldPhone.setMaximumSize(new java.awt.Dimension(148, 21));
        jTextFieldPhone.setMinimumSize(new java.awt.Dimension(148, 21));
        jTextFieldPhone.setPreferredSize(new java.awt.Dimension(148, 21));

        jTextFieldEmail.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextFieldEmail.setEnabled(false);
        jTextFieldEmail.setMaximumSize(new java.awt.Dimension(148, 21));
        jTextFieldEmail.setMinimumSize(new java.awt.Dimension(148, 21));
        jTextFieldEmail.setPreferredSize(new java.awt.Dimension(148, 21));

        jTextFieldBirthDate.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextFieldBirthDate.setEnabled(false);
        jTextFieldBirthDate.setMaximumSize(new java.awt.Dimension(148, 21));
        jTextFieldBirthDate.setMinimumSize(new java.awt.Dimension(148, 21));
        jTextFieldBirthDate.setPreferredSize(new java.awt.Dimension(148, 21));

        jLabelCustomerEdit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelCustomerEdit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCustomerEdit.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButtonCancelEditCostumer.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButtonCancelEditCostumer.setText("Cancelar");
        jButtonCancelEditCostumer.setEnabled(false);
        jButtonCancelEditCostumer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelEditCostumerActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Id");

        jTextFieldId.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextFieldId.setEnabled(false);
        jTextFieldId.setMaximumSize(new java.awt.Dimension(148, 21));
        jTextFieldId.setMinimumSize(new java.awt.Dimension(148, 21));
        jTextFieldId.setPreferredSize(new java.awt.Dimension(148, 21));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldPhone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldBirthDate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabelCustomerEdit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jButtonSendEditCostumer)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonCancelEditCostumer))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldId, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelCustomerEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldId, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldPhone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldBirthDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSendEditCostumer)
                    .addComponent(jButtonCancelEditCostumer))
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButtonCrear.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButtonCrear.setText("Crear");
        jButtonCrear.setFocusCycleRoot(true);
        jButtonCrear.setMaximumSize(new java.awt.Dimension(100, 23));
        jButtonCrear.setMinimumSize(new java.awt.Dimension(100, 23));
        jButtonCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCrearActionPerformed(evt);
            }
        });

        jButtonModificar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButtonModificar.setText("Modificar");
        jButtonModificar.setFocusCycleRoot(true);
        jButtonModificar.setMaximumSize(new java.awt.Dimension(100, 23));
        jButtonModificar.setMinimumSize(new java.awt.Dimension(100, 23));
        jButtonModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificarActionPerformed(evt);
            }
        });

        jButtonEliminar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButtonEliminar.setText("Eliminar");
        jButtonEliminar.setFocusCycleRoot(true);
        jButtonEliminar.setMaximumSize(new java.awt.Dimension(100, 23));
        jButtonEliminar.setMinimumSize(new java.awt.Dimension(100, 23));
        jButtonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Operación");
        jLabel8.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButtonListAll.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButtonListAll.setText("Listar todos");
        jButtonListAll.setFocusCycleRoot(true);
        jButtonListAll.setMaximumSize(new java.awt.Dimension(100, 23));
        jButtonListAll.setMinimumSize(new java.awt.Dimension(100, 23));
        jButtonListAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonListAllActionPerformed(evt);
            }
        });

        jButtonIdSearch.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButtonIdSearch.setText("Buscar por Id");
        jButtonIdSearch.setFocusCycleRoot(true);
        jButtonIdSearch.setMaximumSize(new java.awt.Dimension(100, 23));
        jButtonIdSearch.setMinimumSize(new java.awt.Dimension(100, 23));
        jButtonIdSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIdSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonIdSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonListAll, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCrear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonListAll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonIdSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButtonEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jMenuFile.setText("Fichero");
        jMenuFile.setActionCommand("");

        jMenuExit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuExit.setText("Salir");
        jMenuExit.setToolTipText("");
        jMenuExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuExitActionPerformed(evt);
            }
        });
        jMenuFile.add(jMenuExit);

        jMenuBar1.add(jMenuFile);

        jMenuHelp.setText("Ayuda");

        jMenuAbout.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuAbout.setText("Acerca de...");
        jMenuAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuAboutActionPerformed(evt);
            }
        });
        jMenuHelp.add(jMenuAbout);

        jMenuBar1.add(jMenuHelp);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelTable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanelTable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuExitActionPerformed

    private void jMenuAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuAboutActionPerformed
        JOptionPane.showMessageDialog(null, "Aplicacion desarrollada por Cristian Ade");
    }//GEN-LAST:event_jMenuAboutActionPerformed

    private void jButtonClearFiltersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClearFiltersActionPerformed
        if(!jTextFieldFilter.getText().isEmpty()){
        jTextFieldFilter.setText(null);
        sorter.setRowFilter(null);
        }
    }//GEN-LAST:event_jButtonClearFiltersActionPerformed

    private void jButtonSendEditCostumerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSendEditCostumerActionPerformed

        Customer customer;
        
        int id;
        String name = jTextFieldName.getText();
        String phone = jTextFieldPhone.getText();
        String email = jTextFieldEmail.getText();
        String birthDate = jTextFieldBirthDate.getText();
        String operacion = jLabelCustomerEdit.getText();
        
        
        
    switch (operacion) {

            case "Crear":
                customer = new Customer(name, phone, email, birthDate);
                jTextFieldMessages.setText(guiMainController.createCustomer(customer));
                populateCustomerTable();
                clearMessageBox();
                break;

            case "Modificar":
                id = Integer.parseInt(jTextFieldId.getText());
                customer = new Customer(id, name, phone, email, birthDate);
                jTextFieldMessages.setText(guiMainController.modifyCustomer(customer));
                populateCustomerTable();
                clearMessageBox();
                break;

            case "Eliminar":
                id = Integer.parseInt(jTextFieldId.getText());
                customer = new Customer(id, name, phone, email, birthDate);
                int confirmacion = JOptionPane.showConfirmDialog(null, "Desea borrar el cliente");
                if(confirmacion==0){
                    jTextFieldMessages.setText(guiMainController.deleteCustomer(customer));
                populateCustomerTable();
                } else {
                    jTextFieldMessages.setText("No se eliminó al cliente");  
                }
                clearMessageBox();
                break;

            case "Busqueda por Id":
                try {
                    id = Integer.parseInt(jTextFieldId.getText());
                    customer = new Customer(id, name, phone, email, birthDate);
                    jTableDefaultModel = (DefaultTableModel) jTableCustomer.getModel();
                    jTableDefaultModel.setRowCount(0);
                    jTableDefaultModel.addRow(guiMainController.searchCustomerById(customer));
                    jTextFieldId.setEditable(false);
                } catch (Exception e) {
                    jTextFieldMessages.setText("Debe introducir un numero entre 1 y " + jTableDefaultModel.getRowCount());
                    clearMessageBox();
                }
            clearMessageBox();
            break;
        }
        clearCustomerEdit();
        disableCustomerEdit();

    }//GEN-LAST:event_jButtonSendEditCostumerActionPerformed

    private void jTextFieldFilterKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldFilterKeyTyped
        filterTable();
    }//GEN-LAST:event_jTextFieldFilterKeyTyped

    private void jTableCustomerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableCustomerMouseClicked
        if(!jLabelCustomerEdit.getText().equalsIgnoreCase("Crear")){
        int row = jTableCustomer.getSelectedRow();
        String id = jTableCustomer.getModel().getValueAt(row, 0).toString();
        String nombre = jTableCustomer.getModel().getValueAt(row, 1).toString();
        String telefono = jTableCustomer.getModel().getValueAt(row, 2).toString();
        String correo = jTableCustomer.getModel().getValueAt(row, 3).toString();
        String fechaNac = jTableCustomer.getModel().getValueAt(row, 4).toString();
        
        jTextFieldId.setText(id);
        jTextFieldName.setText(nombre);
        jTextFieldPhone.setText(telefono);
        jTextFieldEmail.setText(correo);
        jTextFieldBirthDate.setText(fechaNac);
        }
    }//GEN-LAST:event_jTableCustomerMouseClicked

    private void jButtonCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCrearActionPerformed
        if(!editTextFields){
        jLabelCustomerEdit.setText("Crear");
        enableCustomerEdit();
        clearCustomerEdit();
        }
    }//GEN-LAST:event_jButtonCrearActionPerformed

    private void jButtonCancelEditCostumerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelEditCostumerActionPerformed
        disableCustomerEdit();
        clearCustomerEdit();
    }//GEN-LAST:event_jButtonCancelEditCostumerActionPerformed

    private void jButtonModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificarActionPerformed
        if(jTableCustomer.getSelectedRow()>-1 & !editTextFields & !jTextFieldId.getText().equalsIgnoreCase("")){
        jLabelCustomerEdit.setText("Modificar");
        enableCustomerEdit();
        }
    }//GEN-LAST:event_jButtonModificarActionPerformed

    private void jButtonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarActionPerformed
        if(jTableCustomer.getSelectedRow()>-1 & !editTextFields & !jTextFieldId.getText().equalsIgnoreCase("")){
        jLabelCustomerEdit.setText("Eliminar");
        deleteCustomerEdit();
        }
    }//GEN-LAST:event_jButtonEliminarActionPerformed

    private void jButtonListAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonListAllActionPerformed
        populateCustomerTable();        
    }//GEN-LAST:event_jButtonListAllActionPerformed

    private void jButtonIdSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIdSearchActionPerformed
        if(!editTextFields){
        clearCustomerEdit();
        jLabelCustomerEdit.setText("Busqueda por Id");
        editTextFields = true;
        jTextFieldId.setEnabled(true);
        jTextFieldId.setEditable(true);
        jButtonSendEditCostumer.setEnabled(true);
        jButtonCancelEditCostumer.setEnabled(true);
    }
        
    }//GEN-LAST:event_jButtonIdSearchActionPerformed

    private void jTextFieldMessagesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldMessagesKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMessagesKeyTyped

    public void filterTable() {
        
        sorter = new TableRowSorter<TableModel>(jTableDefaultModel);
        String text = jTextFieldFilter.getText();
        jTableCustomer.setRowSorter(sorter);
        sorter.setRowFilter(RowFilter.regexFilter(text));
        
    }
  
   
    
    public void idSearchCustomerTable(int uId) throws IOException {
        int id = uId;
        jTableDefaultModel = (DefaultTableModel) jTableCustomer.getModel();
        jTableDefaultModel.setRowCount(0);
        Data d = userApiService.getSingleUser(id);

        id = d.getId();
        String nombre = d.getFirst_name();
        String telefono = d.getLast_name();
        String correo = d.getEmail();
        String fecha = "02/03";

        Object o[] = {id, nombre, telefono, correo, fecha};
        
        jTableDefaultModel.addRow(o);

    }
    
    public void populateCustomerTable(){
        
        jTableDefaultModel = (DefaultTableModel) jTableCustomer.getModel();
        jTableDefaultModel.setRowCount(0);
        ArrayList<Datum> customers = null;
        try {
            customers = userApiService.getAllUserRequest();
        } catch (IOException ex) {
            Logger.getLogger(GuiMain.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        for (Datum p : customers) {

                int id = p.getId();
                String nombre = p.getFirst_name();
                String telefono = p.getLast_name();
                String correo = p.getEmail();
                String fecha = "02/03";
                
                Object o[] = {id, nombre, telefono, correo, fecha};
                
                jTableDefaultModel.addRow(o);   
                                  
                }
    }
    
    public void enableCustomerEdit(){
       editTextFields = true;
       jTextFieldName.setEnabled(true);
       jTextFieldPhone.setEnabled(true);
       jTextFieldEmail.setEnabled(true);
       jTextFieldBirthDate.setEnabled(true);
       jTextFieldId.setEditable(true);
       jTextFieldName.setEditable(true);
       jTextFieldPhone.setEditable(true);
       jTextFieldEmail.setEditable(true);
       jTextFieldBirthDate.setEditable(true);
       jButtonSendEditCostumer.setEnabled(true);
       jButtonCancelEditCostumer.setEnabled(true);
    }
    
    public void deleteCustomerEdit(){
       enableCustomerEdit();
       jTextFieldId.setEnabled(true);
       jTextFieldId.setEditable(false);
       jTextFieldName.setEditable(false);
       jTextFieldPhone.setEditable(false);
       jTextFieldEmail.setEditable(false);
       jTextFieldBirthDate.setEditable(false);
       jButtonSendEditCostumer.setEnabled(true);
       jButtonCancelEditCostumer.setEnabled(true);
    }
    
    public void disableCustomerEdit(){
       editTextFields = false;
       jLabelCustomerEdit.setText("");
       jTextFieldId.setEnabled(false);
       jTextFieldName.setEnabled(false);
       jTextFieldPhone.setEnabled(false);
       jTextFieldEmail.setEnabled(false);
       jTextFieldBirthDate.setEnabled(false);
       jButtonSendEditCostumer.setEnabled(false);
       jButtonCancelEditCostumer.setEnabled(false);
  
    }
    
    private void clearCustomerEdit(){
        jTextFieldId.setText("");
        jTextFieldName.setText("");
        jTextFieldPhone.setText("");
        jTextFieldEmail.setText("");
        jTextFieldBirthDate.setText("");
    }
    
    private void clearMessageBox() {
        Timer timer = new Timer(2000, taskPerformer);
        timer.setRepeats(false);
        timer.start();
        taskPerformer = new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jTextFieldMessages.setText("");
            }
        };
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuiMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuiMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuiMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuiMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new GuiMain().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(GuiMain.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
   
                
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelEditCostumer;
    private javax.swing.JButton jButtonClearFilters;
    private javax.swing.JButton jButtonCrear;
    private javax.swing.JButton jButtonEliminar;
    private javax.swing.JButton jButtonIdSearch;
    private javax.swing.JButton jButtonListAll;
    private javax.swing.JButton jButtonModificar;
    private javax.swing.JButton jButtonSendEditCostumer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelCustomerEdit;
    private javax.swing.JMenuItem jMenuAbout;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuExit;
    private javax.swing.JMenu jMenuFile;
    private javax.swing.JMenu jMenuHelp;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelTable;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableCustomer;
    private javax.swing.JTextField jTextFieldBirthDate;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldFilter;
    private javax.swing.JTextField jTextFieldId;
    private javax.swing.JTextField jTextFieldMessages;
    private javax.swing.JTextField jTextFieldName;
    private javax.swing.JTextField jTextFieldPhone;
    // End of variables declaration//GEN-END:variables

    
}
